# Nixpacks Plan
[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build phase - skipping collectstatic (ser√° feito no release)"']

[start]
cmd = 'gunicorn mediaexpand.wsgi --log-file -'
